# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mixingBowlApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients_On_Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='mixingBowlApp.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='mixingBowlApp.Recipe')),
            ],
        ),
    ]
